
num_traj: 1
use_planner: true

MPC:
  N: 50
  dt: 0.1
  SQP_iters: 1
  stateRefScaling: [0, 0, 0, 0]
  stateGoalScaling: [1, 1, 1, 1]
  path_length_cost: [10, 10, 100, 100]
  terminalScaling: [1, 1, 1, 1]
  inputScaling: [.1, .1]
  tau_max: 5
  vel_max: 0.2
  

Planner:
  bez_dt: 0.5
  buffer: 0.0
  num_points: 5000
  x_bounds: [-4,4, -4, 4] # min_x, max_x, min_y, max_y
  dx_bounds: [0, 0, 0, 0] # min_dx, max_dx, min_dy, max_dy
  log_edges: false
  use_zed: false
  use_random_grid:  false
