
num_traj: 100

MPC:
  N: 30
  dt: 1.0
  SQP_iters: 5
  stateScaling: [1, 1, 10, 10]
  inputScaling: [10, 10]
  terminalScaling: 10
  tau_max: 5
  use_previous_reference: true

Planner:
  num_points: 500
  x_bounds: [-3, 3, -3, 3] # min_x, max_x, min_y, max_y
  dx_bounds: [0, 0, 0, 0] # min_dx, max_dx, min_dy, max_dy
  log_edges: false